config/routes.rb
Rails.application.routes.draw do

  devise_for :accounts
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/backoffice', as: 'rails_admin'

  root 'home#index'

  get 'contact' => 'home#contact'
  get 'about-us' => 'about#index'

  get 'about/index'
  get 'about/difference'
  get 'about/timeline'
  get 'about/vision'
  get 'about/specialists'
  get 'about/structure'
  get 'about/board'
  get 'about/partners'
  get 'about/careers'
  get 'about/reports'
  get 'about/periodics'
  get 'about/media'
  get 'about/video'
  get 'about/testimonials'

  get 'services/index'
  get 'services/show'

  get 'departments' => 'departments#index'
  get 'departments/:category' => 'departments#category', as: :department_category
  get 'departments/:category/:id' => 'departments#show', as: :department_category_department, controller: :departments
  get 'departments/:category/:id/about' => 'departments#about', as: :about_department
  get 'departments/:category/:id/patients' => 'departments#patients', as: :department_patients
  get 'departments/:category/:id/specialists' => 'departments#specialists', as: :department_specialists
  get 'departments/:category/:id/achievements' => 'departments#achievements', as: :department_achievements
  get 'departments/:category/:id/publications' => 'departments#publications', as: :department_publications
  get 'departments/:category/:id/in-the-press' => 'departments#press', as: :department_press

  get 'news' => 'news#index'
  get 'news/:id' => 'news#show', as: :news_item

end

app/views/shared/_about_sidenav.html.erb
<nav class="sidenav">
  <ul>
    <li>
      <a href='#'>
        Чим ми відрізняемось
      </a>
    </li>
    <li>
      <a href='/timeline.html'>
        Наша історія
      </a>
    </li>
    <li>
      <a href='/about-us/Our-Vision.html'>
        Наше бачення
      </a>
    </li>
    <li>
      <a href='/about-us/Lead-Researchers.html'>
        Провідні фахівці
      </a>
    </li>
    <li>
      <a href='/about-us/Governance.html'>
        Структура
      </a>
    </li>
    <li>
      <a href='/about-us/Board-Members.html'>
        Керівництво
      </a>
    </li>
    <li>
      <a href='/about-us/Affiliations-and-Partnerships.html'>
        Партнери
      </a>
    </li>
    <li>
      <a href='/about-us/Job-Vacancies-and-Careers.html'>
        Кар'ера у нас
      </a>
    </li>
    <li>
      <a href='/about-us/Annual-Reports-and-Financial-Statements.html'>
        Державні закупівлі
      </a>
    </li>
    <li>
      <a href='/about-us/Newsletter-Archive.html'>
        Періодичні видання
      </a>
    </li>
    <li>
      <a href='/about-us/In-the-Media.html'>
        В пресі
      </a>
    </li>
    <li>
      <a href='/about-us/Videos.html'>
        Відео
      </a>
    </li>
    <li>
      <a href='#'>
        Відгуки пацієнтів
      </a>
    </li>
  </ul>
</nav>

app/views/shared/_departments_sidenav.html.erb
<nav class="sidenav">
  <ul>
    <% @categories.each_with_index do |cat, idx| %>
        <%- cat_match = request.original_fullpath.include? department_category_path(cat) %>
        <li class="<%= 'active' if cat_match %>">
          <a href="<%= department_category_path(cat) %>"><%= cat.name %></a>
          <% if cat.departments.present? %>
              <ul class="sub-menu" style="<%= 'display: block;' if cat_match %>">
                <% cat.departments.each do |dept| %>
                    <%- dept_match = (request.original_fullpath+'/').include? (department_category_department_path(cat, dept)+'/') %>
                    <li class="<%= 'active' if cat_match %>">
                      <%= link_to dept.name, [cat, dept] %>
                      <ul class="sub-menu" style="<%= 'display: block;' if dept_match %>">
                        <li class="<%= 'active' if current_page? about_department_path(cat, dept) %>" >
                          <a href="<%= about_department_path(cat, dept) %>">Про відділення</a>
                        </li>

                        <li class="<%= 'active' if current_page? department_patients_path(cat, dept) %>">
                          <a href="<%= department_patients_path(cat, dept) %>">Пацієнтам</a>
                        </li>

                        <li class="<%= 'active' if current_page? department_specialists_path(cat, dept) %>">
                          <a href="<%= department_specialists_path(cat, dept) %>">Фахівці</a>
                        </li>

                        <li class="<%= 'active' if current_page? department_achievements_path(cat, dept) %>">
                          <a href="<%= department_achievements_path(cat, dept) %>">Досягнення</a>
                        </li>

                        <li class="<%= 'active' if current_page? department_publications_path(cat, dept)  %>">
                          <a href="<%= department_publications_path(cat, dept) %>">Публікації</a>
                        </li>

                        <li class="<%= 'active' if current_page? department_press_path(cat, dept)  %>">
                          <a href="<%= department_press_path(cat, dept) %>">Преса про нас</a>
                        </li>
                      </ul>
                    </li>
                <% end %>
              </ul>
          <% end %>
        </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_departments_subpage.html.erb
<div class="clearfix"></div>

<div class="leftContentInside">
  <h1><%= page.title %></h1>

  <%= raw page.content %>
</div>


<div class="rightContentSidebar">
  <div class="sidebar-widget blue">

    <div>
      <div class="widgetname">
        <h3>
          Зміст</h3>
        <ul>
          <li>
            <a href="#chromatin">Lorem ipsum dolor</a></li>
          <li>
            <a href="#ALTgenes">Lorem dolor repellat</a></li>
          <li>
            <a href="#normal">Beatae consectetur et</a></li>
        </ul>

      </div>
      <div class="line"></div>
    </div>


    <div id="rhsBottom" class="widgetname">
      <img alt=""
           src="/images/treatment/entry1.png"
           style="width: 215px; height: 215px;" title="Хірургічне відділення"/>
      <address>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
      </address>

    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="leftfoot">
        <div class="connect">
          <h4>Феофанія в соціальних мережах</h4>
          <ul class="share-links">
            <li><a href='https://www.facebook.com/feofania' target='_blank'><i
            class='icon-facebook'></i></a></li>
            <li><a href='https://twitter.com/feofania' target='_blank'><i class='icon-twitter'></i></a>
            </li>
            <li><a href='http://www.youtube.com/user/feofania' target='_blank'><i
            class='icon-youtube'></i></a></li>
            <li><a href='http://instagram.com/feofania' target='_blank'><i
            class='icon-instagram'></i></a></li>
          </ul>
        </div>
        <!--/connect-->
        <div class="line"></div>
        <div class="subscribe">
          <h4>Підпишіться на Новини</h4>

          <p>Отримуйте остнні новини так пропозиції</p>

          <div class="form" id="formSubscribe"
               onkeypress="javascript:return WebForm_FireDefaultButton(event, 'uiBtnSubscribe');">
            <input type="text" placeholder="Вкажіть email" id="uiTxtEmmail" name="uiTxtEmmail"><input
          type="button" class="btn btn-black" value="Готово" id="uiBtnSubscribe"
          name="uiBtnSubscribe" onclick="subscribe(); return false">
          </div>
        </div>
      </div>
      <!--/leftfoot-->

      <div class="centerfoot">
        <div class="contact">
          <h4 id="contact-bottom">Контакт з нами</h4>
          <dl>
            <dt class="phone"> Телефон:</dt>
            <dd>
              <a href="tel://+380 44 259 6977"><span class="btn-phone"><i class="icon-phone"></i> +380 44 259 6977</span></a>
              <br></dd>
            <dt> Email:</dt>
            <dd><a href="mailto:info@feofaniya.org">info@feofaniya.org</a><br></dd>
            <dt> Факс:</dt>
            <dd>+380 44 259 6977</dd>
          </dl>
          <p>Поштова адреса<br/>
            Академіка Заболотного, 21<br/>
            03680, Київ, Україна</p>
        </div>
        <!--/contact-->
        <div class="line"></div>
        <div class="gmap">
          <h4>Знайти на мапі <a
          href="https://maps.google.com/maps?q=Академіка Заболотного, 21, 03680, Київ, Україна"
          title="FEOFANIA on Google Map" target="_blank"><i class="icon-openlink"></i></a></h4>

          <p>Адреса<br/>
            Академіка Заболотного, 21<br/>
            03680, Київ, Україна</p>

          <div class="map">
            <a href="https://maps.google.com/maps?q=Академіка Заболотного, 21, 03680, Київ, Україна"
               title="Feofaniya on Google Map" target="_blank"><img
            src="/images/map.jpg?width=350&amp;height=260&amp;ext=.jpg"
            alt="Feofaniya Map"/></a>
          </div>
        </div>
      </div>
      <!--/centerfoot-->

      <div class="rightfoot">
        <div class="staff-login">
          <h4>Для персоналу</h4>

          <div class="form"
               onkeypress="">
            <div class="staff-name"><input type="text" placeholder="Логін чи Email" id="uiTxtUsername"
                                           name="uiTxtUsername"></div>
            <div class="staff-pwd"><input type="password" placeholder="Пароль" id="uiTxtPassword"
                                          name="uiTxtPassword"></div>
            <div class="staff-remember">
              <input type="checkbox" name="uiChkRemember" id="uiChkRemember" value="Yes"
                     checked><label
            for="uiChkRemember"> Запом'ятати мене</label>
              <input type="button" class="btn btn-black" value="Увійти" ID="uiBtnLogin"
                     name="uiBtnLogin" onclick="login();return false;"/>
            </div>
            <div id="loginError"></div>
            <br><br><br>

            <div class="forgot-password"><a href="mailto:admin@feofaniya.org?subject=login"><i
            class="icon-arrow"></i>Забули пароль?</a></div>
          </div>
        </div>
        <!--/staff-login-->
      </div>
      <!--/rightfoot-->

    </div>
  </div>

  <div class="line"></div>

  <div class="container">
    <div class="footlogo"><img src="/images/logo-bottom.png" alt="Феофанія"></div>
    <div class="footcopy">
      <ul>

        <li><a href="/sitemap.html">Мапа сайту</a></li>
        <li><a href="/privacy.html">Умови користування сервісом</a></li>
        <li><a href="/contact.html">Контакти</a></li>

        <li>&copy; 2014 Феофанія</li>
      </ul>
    </div>
    <div class="footslogan">
      <h4>Клінічна Лікарня "Феофанія"</h4>
    </div>
    <div class="phar">
      <a href="http://phar.com.ua" title="Создать сайт" target="_blank">Розробка сайту</a>
      <a href="http://phar.com.ua" title="Создать сайт Киев" target="_blank"><img
      src="/images/phar_logo.png" alt="PHAR - разработка сайтов"/></a>
    </div>
    <div class="select-language" style="display: none">
      <select id="languages">
        <option>Вибір мови</option>
        <option>English</option>
        <option>Chinese</option>
        <option>Spain</option>
        <option>France</option>
      </select>
    </div>

    <div class="clearfix"></div>
  </div>
</footer>

app/views/shared/_grid.html.erb
<div class="box">
  <div class="pic" style="">
    <%= link_to [@category, item] do %>
        <span></span>
        <img src="<%= item.try(:thumbnail) || item.image %>"
             alt="<%= item.name %>">
    <% end %>
  </div>
  <h3>
    <%= link_to item.name, [@category, item] %>
  </h3>

  <p><%= raw item.description %></p>
</div>

app/views/shared/_menu.html.erb
<ul class="mega-menu">

  <li class='two-col drop'>
    <a href="/about-us.html">
      О Феофанії
    </a>

    <div class="submenu" style="display: none;">
                <span class="toparrow">
                </span>
      <a href="/about-us.html">
        <h2>
          <svg class="svg-profile" viewBox="0 0 32 32">
            <g filter="">
              <use xlink:href="#icon-profile">
              </use>
            </g>
          </svg>
          Про заклад
        </h2>
      </a>

      <div class='subcols c1'>
        <ul>
          <li>
            <a href='#'>
              Чим ми відрізняемось
            </a>
          </li>
          <li>
            <a href='/timeline.html'>
              Наша історія
            </a>
          </li>
          <li>
            <a href='/about-us/Our-Vision.html'>
              Наше бачення
            </a>
          </li>
          <li>
            <a href='/about-us/Lead-Researchers.html'>
              Провідні фахівці
            </a>
          </li>
          <li>
            <a href='/about-us/Governance.html'>
              Структура
            </a>
          </li>
          <li>
            <a href='/about-us/Board-Members.html'>
              Керівництво
            </a>
          </li>
        </ul>
      </div>
      <div class='subcols c2'>
        <ul>
          <li>
            <a href='/about-us/Affiliations-and-Partnerships.html'>
              Партнери
            </a>
          </li>
          <li>
            <a href='/about-us/Job-Vacancies-and-Careers.html'>
              Кар'ера у нас
            </a>
          </li>
          <li>
            <a href='/about-us/Annual-Reports-and-Financial-Statements.html'>
              Державні закупівлі
            </a>
          </li>
          <li>
            <a href='/about-us/Newsletter-Archive.html'>
              Періодичні видання
            </a>
          </li>
          <li>
            <a href='/about-us/In-the-Media.html'>
              В пресі
            </a>
          </li>
          <li>
            <a href='/about-us/Videos.html'>
              Відео
            </a>
          </li>
          <li>
            <a href='#'>
              Відгуки пацієнтів
            </a>
          </li>
        </ul>
      </div>
    </div>

  </li>

  <li class='drop'>
    <a href="/departments">
      Відділення
    </a>

    <div class="submenu" style="display: none;">
      <span class="toparrow"></span>
      <a href="/departments">
        <h2>
          <svg class="svg-research" viewBox="0 0 62 70">
            <g filter="">
              <use xlink:href="#icon-research">
              </use>
            </g>
          </svg>
          Відділення
        </h2>
      </a>


      <% @categories.each_with_index do |cat, idx| %>
          <div class="subcols c<%= idx %>">
            <a href='<%= department_category_path(cat) %>' class='mega-menu-sectionlink'>
              <h3><%= cat.name %></h3>
            </a>

            <% if cat.departments.present? %>
                <ul>
                  <% cat.departments.each do |dept| %>
                      <li><%= link_to dept.name, [cat, dept] %></li>
                  <% end %>
                </ul>
            <% end %>
          </div>
      <% end %>
    </div>

  </li>

  <li class='two-col'>
    <a href="/directions.html">
      Напрямки
    </a>

    <div class="submenu" style="display: none;">
                <span class="toparrow">
                </span>
      <a href="directions.html">
        <h2>
          <svg class="svg-love" viewBox="0 0 32 32">
            <g filter="">
              <use xlink:href="#icon-love">
              </use>
            </g>
          </svg>
          Оберіть напрямок
        </h2>
      </a>

      <div class='subcols c1'>
        <ul>
          <li>
            <a href='#'>
              Алерген-специфічна імунотерапія
            </a>
          </li>
          <li>
            <a href='#'>
              Алергологія
            </a>
          </li>
          <li>
            <a href='#'>
              Анестезія та інтенсивна терапія
            </a>
          </li>
          <li>
            <a href='#'>
              Вакцинація
            </a>
          </li>
          <li>
            <a href='#'>
              Ведення вагітності
            </a>
          </li>
          <li>
            <a href='#'>
              Гастроскопія
            </a>
          </li>
        </ul>
      </div>
      <div class='subcols c2'>
        <ul>
          <li>
            <a href='#'>
              Гастроентерологія
            </a>
          </li>
          <li>
            <a href='#'>
              Гепатологія
            </a>
          </li>
          <li>
            <a href='#'>
              Гінекологія
            </a>
          </li>
          <li>
            <a href='#'>
              Дерматологія
            </a>
          </li>
          <li>
            <a href='#'>
              Діагностика інсульту
            </a>
          </li>
          <li>
            <a href='#'>
              Дієтологія
            </a>
          </li>
          <li>
            <a href='#'>
              Інсульт
            </a>
          </li>
          <li>
            <a href='#'>
              Кардіологія
            </a>
          </li>
        </ul>
      </div>
    </div>

  </li>

  <li class='one-col'>
    <a href="/Research-Explained.html">
      Дослідження
    </a>

    <div class="submenu" style="display: none;">
      <span class="toparrow"></span>
      <a href="Research-Explained.html">
        <h2>
          <svg class="svg-date" viewBox="0 0 55 60">
            <g filter="">
              <use xlink:href="#icon-lamp">
              </use>
            </g>
          </svg>
          Лікарям
        </h2>
      </a>

      <div class='subcols c1'>
        <ul>

          <li>
            <a href='#'>
              Семінари
            </a>
          </li>

          <li>
            <a href='#'>
              Тренінги та Симпозіуми
            </a>
          </li>

          <li>
            <a href='#'>
              Обладнання
            </a>
          </li>

          <li>
            <a href='#'>
              Сертифікація
            </a>
          </li>

        </ul>
      </div>
    </div>

  </li>

  <li class='one-col'>
    <a href="#">
      Пацієнту
    </a>

    <div class="submenu" style="display: none;">
      <span class="toparrow"></span>
      <a href="#">
        <h2>
          <svg class="svg-date" viewBox="0 0 60 60">
            <g filter="">
              <use xlink:href="#icon-date">
              </use>
            </g>
          </svg>
          Пацієнту
        </h2>
      </a>

      <div class='subcols c1'>
        <ul>

          <li>
            <a href='#'>
              Запис на прийом
            </a>
          </li>

          <li>
            <a href='#'>
              Захворювання
            </a>
          </li>

          <li>
            <a href='#'>
              Программи обстеження
            </a>
          </li>

          <li>
            <a href='#'>
              Результати аналізів
            </a>
          </li>

          <li>
            <a href='#'>
              Ціни на послуги
            </a>
          </li>

          <li>
            <a href='#'>
              Донорство
            </a>
          </li>

          <li>
            <a href='#'>
              Запитання та відповіді
            </a>
          </li>

        </ul>
      </div>
    </div>

  </li>

  <li class=''>
    <a href="/news">
      Новини
    </a>
  </li>

  <li class='one-col'>
    <a href="/contact.html">
      Контакти
    </a>

    <div class="submenu" style="display: none;">
                <span class="toparrow">
                </span>
      <a href="/contact.html">
        <h2>
          <svg class="svg-contact" viewBox="0 0 50 50">
            <g filter="">
              <use xlink:href="#icon-contact">
              </use>
            </g>
          </svg>
          Контакт
        </h2>
      </a>

      <div class='subcols c1'>
        <ul>
          <li>
            <a href='/contact/For-Media.html'>
              Для преси
            </a>
          </li>
        </ul>
      </div>
    </div>

  </li>

  <li class="search">
    <a href="#"><i class="icon-search"></i></a>

    <div class="submenu" onkeypress="" style="display: none;">
                                    <span class="toparrow">
                                    </span>
      <input type="text" placeholder="Введіть пошуковий запит" id="uiTxtSearchText"
             name="uiTxtSearchText" onkeypress="return SearchEnterEvent(event)"/>
      <input type="submit" value="Пошук" class="btn" id="uiBtnSearch" name="uiBtnSearch"
             onclick="RedirectToSearchPage(); return false;">

    </div>
  </li>
</ul>

app/views/shared/_sidebar_mobile.html.erb
<aside class="sidebar-mobile">
  <div class="search">
    <div class="form">
      <input type="text" placeholder="Введіть пошуковий запит" id="uiTxtSearchMobile"
             onkeypress="return SearchEnterEventMobile(event)">
    </div>
  </div>
  <nav>
    <ul>
      <li>
        <a href="/about-us.html">
          <svg class="svg-icon about" viewBox="0 0 32 32">
            <g filter="">
              <use xlink:href="#icon-profile">
              </use>
            </g>
          </svg>
          Про заклад
        </a>
        <ul>
          <li>
            <a href='/about-us/difference.html'>
              Чим ми відрізняемось
            </a>
          </li>
          <li>
            <a href='/timeline.html'>
              Наша історія
            </a>
          </li>
          <li>
            <a href='/about-us/Our-Vision.html'>
              Наше бачення
            </a>
          </li>
          <li>
            <a href='/about-us/Lead-Researchers.html'>
              Провідні фахівці
            </a>
          </li>
          <li>
            <a href='/about-us/Governance.html'>
              Структура
            </a>
          </li>
          <li>
            <a href='/about-us/Board-Members.html'>
              Керівництво
            </a>
          </li>
          <li>
            <a href='/about-us/Affiliations-and-Partnerships.html'>
              Партнери
            </a>
          </li>
          <li>
            <a href='/about-us/Job-Vacancies-and-Careers.html'>
              Кар'ера у нас
            </a>
          </li>
          <li>
            <a href='/about-us/Annual-Reports-and-Financial-Statements.html'>
              Державні закупівлі
            </a>
          </li>
          <li>
            <a href='/about-us/Newsletter-Archive.html'>
              Періодичні видання
            </a>
          </li>
          <li>
            <a href='/about-us/In-the-Media.html'>
              В пресі
            </a>
          </li>
          <li>
            <a href='/about-us/Videos.html'>
              Відео
            </a>
          </li>
          <li>
            <a href='#'>
              Відгуки пацієнтів
            </a>
          </li>
        </ul>
      </li>

      <li>
        <a href="/departments.html">
          <svg class="svg-icon lab" viewBox="0 0 60 60">
            <g filter="">
              <use xlink:href="#icon-research">
              </use>
            </g>
          </svg>
          Відділення
        </a>
        <ul>
          <% @categories.each_with_index do |cat, idx| %>
              <%- cat_match = request.original_fullpath.include? department_category_path(cat) %>
              <li class="<%= 'active' if cat_match %>">
                <a href="<%= department_category_path(cat) %>"><%= cat.name %></a>
              </li>
          <% end %>
        </ul>
      </li>

      <li>
        <a href="directions.html">
          <svg class="svg-icon" viewBox="0 0 31 31">
            <g filter="">
              <use xlink:href="#icon-love">
              </use>
            </g>
          </svg>
          Напрямки
        </a>
        <ul>
          <li>
            <a href='#'>
              Алерген-специфічна імунотерапія
            </a>
          </li>
          <li>
            <a href='#'>
              Алергологія
            </a>
          </li>
          <li>
            <a href='#'>
              Анестезія та інтенсивна терапія
            </a>
          </li>
          <li>
            <a href='#'>
              Вакцинація
            </a>
          </li>
          <li>
            <a href='#'>
              Ведення вагітності
            </a>
          </li>
          <li>
            <a href='#'>
              Гастроскопія
            </a>
          </li>
        </ul>
      </li>

      <li>
        <a href="Research-Explained.html">
          <svg class="svg-icon lamp" viewBox="0 0 55 60">
            <g filter="">
              <use xlink:href="#icon-lamp">
              </use>
            </g>
          </svg>
          Дослідження
        </a>
        <ul>
          <li>
            <a href='#'>
              Семінари
            </a>
          </li>

          <li>
            <a href='#'>
              Тренінги та Симпозіуми
            </a>
          </li>

          <li>
            <a href='#'>
              Обладнання
            </a>
          </li>

          <li>
            <a href='#'>
              Сертифікація
            </a>
          </li>
        </ul>
      </li>

      <li>
        <a href="Events.html">
          <svg class="svg-icon" viewBox="0 0 60 60">
            <g filter="">
              <use xlink:href="#icon-date">
              </use>
            </g>
          </svg>
          Паціенту
        </a>

      </li>

      <li>
        <a href="news.html">
          <svg class="svg-icon" viewBox="0 0 60 60">
            <g filter="">
              <use xlink:href="#icon-news">
              </use>
            </g>
          </svg>
          Новини
        </a>

      </li>

      <li>
        <a href="/contact.html">
          <svg class="svg-icon" viewBox="0 0 45 45">
            <g filter="">
              <use xlink:href="#icon-contact">
              </use>
            </g>
          </svg>
          Контакти
        </a>
        <ul>
          <li>
            <a href='/contact/For-Media.html'>
              Для преси
            </a>
          </li>
        </ul>
      </li>
    </ul>
    <div class="slide-registry">
      <a href="registry.html" class="btn btn-red">
        Реєстратура
        <i class="icon-arrow">
        </i>
      </a>
    </div>
  </nav>
</aside>

app/views/shared/_title_section.html.erb
<div class="title-section <%= color %>">
  <div class="container">
    <div class="row">

      <%= breadcrumbs pretext: '',
                      separator: '<i>&gt;</i>' %>

      <h2><%= title %></h2>

      <div class="page-icon">
        <%= raw icon %>
      </div>

    </div>
  </div>
</div>