config/routes.rb
Rails.application.routes.draw do

  devise_for :accounts
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/backoffice', as: 'rails_admin'

  root 'home#index'

  get 'contact' => 'home#contact'
  get 'about-us' => 'about#index'

  get 'about/index'
  get 'about/difference'
  get 'about/timeline'
  get 'about/vision'
  get 'about/specialists'
  get 'about/structure'
  get 'about/board'
  get 'about/partners'
  get 'about/careers'
  get 'about/reports'
  get 'about/periodics'
  get 'about/media'
  get 'about/video'
  get 'about/testimonials'

  get 'services/index'
  get 'services/show'

  get 'departments' => 'departments#index'
  get 'departments/:category' => 'departments#category', as: :department_category
  get 'departments/:category/:id' => 'departments#show', as: :department_category_department, controller: :departments
  get 'departments/:category/:id/about' => 'departments#about', as: :about_department
  get 'departments/:category/:id/patients' => 'departments#patients', as: :department_patients
  get 'departments/:category/:id/specialists' => 'departments#specialists', as: :department_specialists
  get 'departments/:category/:id/achievements' => 'departments#achievements', as: :department_achievements
  get 'departments/:category/:id/publications' => 'departments#publications', as: :department_publications
  get 'departments/:category/:id/in-the-press' => 'departments#press', as: :department_press

  get 'news' => 'news#index'
  get 'news/:id' => 'news#show', as: :news_item

end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :category, class_name: 'Department::Category', foreign_key: 'category_id'
  has_and_belongs_to_many :specialities
  has_and_belongs_to_many :services

  has_ancestry

  validates :name, :description, :image, :category, presence: true

  has_attached_file :image, style: {default: "960x400>"}, default_url: "/images/:style/missing.png"
  has_attached_file :thumbnail, styles: {default: "215x215"}, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :image, :thumbnail, :content_type => /\Aimage\/.*\Z/


  default_scope { order(position: :asc) }

  has_one :general_overview,
          class_name: 'Department::General',
          as: :pagable,
          inverse_of: :pagable,
          dependent: :destroy
  has_one :for_patients,
          class_name: 'Department::Patient',
          as: :pagable,
          inverse_of: :pagable,
          dependent: :destroy
  has_one :specialists,
          class_name: 'Department::Specialist',
          as: :pagable,
          inverse_of: :pagable,
          dependent: :destroy
  has_one :achievements,
          class_name: 'Department::Achievement',
          as: :pagable,
          inverse_of: :pagable,
          dependent: :destroy
  has_one :publications,
          class_name: 'Department::Publication',
          as: :pagable,
          inverse_of: :pagable,
          dependent: :destroy
  has_one :in_press,
          class_name: 'Department::Press',
          as: :pagable,
          inverse_of: :pagable,
          dependent: :destroy


  accepts_nested_attributes_for :general_overview, allow_destroy: true
  accepts_nested_attributes_for :for_patients, allow_destroy: true
  accepts_nested_attributes_for :specialists, allow_destroy: true
  accepts_nested_attributes_for :achievements, allow_destroy: true
  accepts_nested_attributes_for :publications, allow_destroy: true
  accepts_nested_attributes_for :in_press, allow_destroy: true

  rails_admin do
    visible do
      label_plural 'Отделения'
      label 'Отделение'
      # weight -1
    end

    nestable_tree({ position_field: :position, max_depth: 3 })

    list do
      field :name do
        label 'Название отделения'
      end

      field :category do
        label 'К какой группе пренадлежит'
      end

      field :specialities do
        label 'Связанные специальности'
      end

      field :services do
        label 'Связанные услуги'
      end

      field :show_in_menu do
        label 'Основное меню'
      end

    end

    edit do
      group :contents do
        label 'Информационные блоки'
      end

      field :name do
        label 'Название отделения'
      end
      field :description, :ck_editor do
        label 'Краткое описание'
      end
      field :introduction, :ck_editor do
        label 'Введение (подробнее)'
      end

      field :image do
        label 'Фотография'
        help 'Основная фотография отделения, 960x400px'
      end

      field :thumbnail do
        label 'Изображение раздела'
        help 'Отображатся при выборе группы отделений, 215х215px'
      end

      field :category do
        label 'К какой группе пренадлежит'
      end
      field :specialities do
        label 'Связанные специальности'
      end
      field :services do
        label 'Связанные услуги'
      end

      field :show_in_menu do
        label 'Показывать в меню'
      end


      field :general_overview do
        label 'Общая информация'
        group :contents
      end
      field :for_patients do
        label 'Для пациентов'
        group :contents
      end
      field :specialists do
        label 'Специалисты отделения'
        group :contents
      end
      field :achievements do
        label 'Достижения'
        group :contents
      end
      field :publications do
        label 'Публикации'
        group :contents
      end
      field :in_press do
        label 'Пресса о отделении'
        group :contents
      end
    end

  end
end

app/models/department/achievement.rb
class Department::Achievement < Page
  rails_admin do
    visible false

    label_plural 'Достижения'
    label 'Информация о достижениях'

    field :title do
      label 'Заголовок'
    end
    field :subtitle do
      label 'Подзаголовок'
    end
    field :content, :ck_editor do
      label 'Содержание'
    end
    field :image do
      label 'Изображение'
    end

  end
end

app/models/department/category.rb
class Department::Category < Category
  has_many :departments

  default_scope { order(position: :asc) }

  rails_admin do
    visible do
      parent Department

      navigation_label 'Отделения'
      label_plural 'Группы отделений'
      label 'Группа отделений'
      # weight -1
    end

    field :name do
      label 'Название группы'
    end

    field :description do
      label 'Краткое описание'
    end

    field :image do
      label 'Иконка группы'
    end

    field :is_active do
      label 'Группа активна?'
    end

    nestable_tree({ position_field: :position, max_depth: 3 })
  end
end

app/models/department/general.rb
class Department::General < Page
  rails_admin do
    visible false

    label_plural 'Общая информация'
    label 'Общая информация'

    field :title do
      label 'Заголовок'
    end
    field :subtitle do
      label 'Подзаголовок'
    end
    field :content, :ck_editor do
      label 'Содержание'
    end
    field :image do
      label 'Изображение'
    end

  end
end

app/models/department/patient.rb
class Department::Patient < Page
  rails_admin do
    visible false

    label_plural 'Пациентам'
    label 'Пациентам'

    field :title do
      label 'Заголовок'
    end
    field :subtitle do
      label 'Подзаголовок'
    end
    field :content, :ck_editor do
      label 'Содержание'
    end
    field :image do
      label 'Изображение'
    end

  end
end

app/models/department/press.rb
class Department::Press < Page
  rails_admin do
    visible false

    label_plural 'Пресса о нас'
    label 'Пресса о нас'

    field :title do
      label 'Заголовок'
    end
    field :subtitle do
      label 'Подзаголовок'
    end
    field :content, :ck_editor do
      label 'Содержание'
    end
    field :image do
      label 'Изображение'
    end

  end
end

app/models/department/publication.rb
class Department::Publication < Page
  rails_admin do
    visible false

    label_plural 'Информация о публикациях'
    label 'Информация о публикациях'

    field :title do
      label 'Заголовок'
    end
    field :subtitle do
      label 'Подзаголовок'
    end
    field :content, :ck_editor do
      label 'Содержание'
    end
    field :image do
      label 'Изображение'
    end

  end
end

app/models/department/specialist.rb
class Department::Specialist < Page
  rails_admin do
    visible false

    label_plural 'Информация о специалистах'
    label 'Информация о специалистах'

    field :title do
      label 'Заголовок'
    end
    field :subtitle do
      label 'Подзаголовок'
    end
    field :content, :ck_editor do
      label 'Содержание'
    end
    field :image do
      label 'Изображение'
    end

  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  layout 'departments'

  before_action :load_department, except: [:index, :category]

  def index
  end

  def category
    @category = @categories.find(params[:category])
    @departments = @category.departments
  end

  def show

  end

  def about

  end

  def patients

  end

  def specialists

  end

  def achievements

  end

  def publications

  end

  def in_the_press

  end

  protected
  def load_department
    @department = Department.find(params[:id])
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/about.html.erb
<% breadcrumb :department_subpage, @department, 'Про відділення' %>

<%= render partial: 'shared/departments_subpage',
           locals: { page: @department.general_overview } if @department.try(:general_overview) %>

app/views/departments/achievements.html.erb
<% breadcrumb :department_subpage, @department, 'Досягнення' %>

<%= render partial: 'shared/departments_subpage',
           locals: { page: @department.achievements } if @department.try(:achievements) %>

app/views/departments/category.html.erb
<% breadcrumb :department_category, @category %>

<div class="clearfix"></div>
<h1></h1>

<div class="intro-content">
  <h2>
  </h2>

  <div class="more-intro">
  </div>
</div>


<div class="entry">
  <div class="boxWrap">
    <%= render partial: 'shared/grid',
               collection: @departments, as: :item
    %>
  </div>
</div>

app/views/departments/index.html.erb
<% breadcrumb :all_departments %>

<div class="clearfix"></div>
<h1>Відділення лікрані "Феофанія"</h1>

<div class="intro-content">
  <h2>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur at
    consequuntur error esse laboriosam nulla repellendus ullam, ut?
  </h2>

  <div class="more-intro">

  </div>
</div>


<div class="entry">
  <div class="boxWrap">
    <%= render partial: 'shared/grid',
               collection: @categories, as: :item if @categories.length
    %>
  </div>
</div>

app/views/departments/patients.html.erb
<% breadcrumb :department_subpage, @department, 'Пацієнтам' %>

<%= render partial: 'shared/departments_subpage',
           locals: { page: @department.for_patients } if @department.try(:for_patients) %>

app/views/departments/press.html.erb
<% breadcrumb :department_subpage, @department, 'Преса про нас' %>

<%= render partial: 'shared/departments_subpage',
           locals: { page: @department.in_press } if @department.try(:in_press) %>

app/views/departments/publications.html.erb
<% breadcrumb :department_subpage, @department, 'Публікації' %>

<%= render partial: 'shared/departments_subpage',
           locals: { page: @department.publications } if @department.try(:publications) %>

app/views/departments/show.html.erb
<% breadcrumb :department, @department %>

<div id="content-slider" class="flexslider">
  <!--<div class="slidecount"><span class="current-slide">1</span> з <span class="total-slides">1</span></div>-->
  <ul class="slides">

    <li>
      <div class="label-bg"></div>
      <!--<div class="label"><%= @department.name %></div>-->
      <img src='<%= @department.image %>'
           alt='<%= @department.name %>'/>
    </li>

  </ul>
  <div class="margin"></div>
</div>

<div class="clearfix"></div>
<h1><%= @department.name %></h1>

<div class="intro-content">
  <h2>
    <%= raw @department.description.presence %>
    <br/><br/>
  </h2>

  <div class="more-intro">
    <%= raw @department.introduction.presence %>
  </div>

  <div id="ctl00_plcMain_showMore" class="show-more">
    <a href="javascript:void(0)" class="btn-more">Детальніше</a>
  </div>
</div>


<div class="research-heading">
  <h3>
    Розділи
  </h3>
</div>


<div class="explore-listing">
  <div class="boxWrap">

    <% if @department.general_overview.present? %>
        <div class="box">
          <article>
            <div class="pic" style="">
              <%= link_to about_department_url do %>
                  <span></span>
                  <img src="<%= @department.general_overview.image(:thumb).presence || '/images/treatment/surgery/entry1.png' %>"
                       alt="Загальна інформація">
              <% end %>
            </div>
            <div class="detail">
              <h3><%= link_to 'Загальна інформація', about_department_url %></h3>
              <p></p>
            </div>
          </article>
        </div>
    <% end %>

    <% if @department.for_patients.present? %>
        <div class="box">
          <article>
            <div class="pic" style="">
              <%= link_to department_patients_url do %>
                  <span></span>
                  <img src="<%= @department.for_patients.image(:thumb).presence || '/images/treatment/surgery/entry2.png' %>"
                       alt="Пацієнтам">
              <% end %>
            </div>
            <div class="detail">
              <h3><%= link_to 'Пацієнтам', department_patients_url %></h3>
              <p></p>
            </div>
          </article>
        </div>
    <% end %>

    <% if @department.specialists.present? %>
        <div class="box">
          <article>
            <div class="pic" style="">
              <%= link_to department_specialists_url do %>
                  <span></span>
                  <img src="<%= @department.specialists.image(:thumb).presence || '/images/treatment/surgery/entry3.png' %>"
                       alt="Фахівці">
              <% end %>
            </div>
            <div class="detail">
              <h3><%= link_to 'Фахівці', department_specialists_url %></h3>
              <p></p>
            </div>
          </article>
        </div>
    <% end %>

    <% if @department.achievements.present? %>
        <div class="box">
          <article>
            <div class="pic" style="">
              <%= link_to department_achievements_url do %>
                  <span></span>
                  <img src="<%= @department.achievements.image(:thumb).presence || '/images/treatment/surgery/entry4.png' %>"
                       alt="Досягнення">
              <% end %>
            </div>
            <div class="detail">
              <h3><%= link_to 'Досягнення', department_achievements_url %></h3>
              <p></p>
            </div>
          </article>
        </div>
    <% end %>

    <% if @department.publications.present? %>
        <div class="box">
          <article>
            <div class="pic" style="">
              <%= link_to department_publications_url do %>
                  <span></span>
                  <img src="<%= @department.publications.image(:thumb).presence || '/images/treatment/surgery/entry5.png' %>"
                       alt="Публікації">
              <% end %>
            </div>
            <div class="detail">
              <h3><%= link_to 'Публікації', department_publications_url %></h3>
              <p></p>
            </div>
          </article>
        </div>
    <% end %>

    <% if @department.in_press.present? %>
        <div class="box">
          <article>
            <div class="pic" style="">
              <%= link_to department_press_url do %>
                  <span></span>
                  <img src="<%= @department.in_press.image(:thumb).presence || '/images/treatment/surgery/entry6.png' %>"
                       alt="Преса про нас">
              <% end %>
            </div>
            <div class="detail">
              <h3><%= link_to 'Преса про нас', department_press_url %></h3>
              <p></p>
            </div>
          </article>
        </div>
    <% end %>

  </div>
</div>

app/views/departments/specialists.html.erb
<% breadcrumb :department_subpage, @department, 'Фахівці' %>

<%= render partial: 'shared/departments_subpage',
           locals: { page: @department.specialists } if @department.try(:specialists) %>