config/routes.rb
Rails.application.routes.draw do

  devise_for :accounts
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/backoffice', as: 'rails_admin'

  root 'home#index'

  get 'contact' => 'home#contact'
  get 'about-us' => 'about#index'

  get 'about/index'
  get 'about/difference'
  get 'about/timeline'
  get 'about/vision'
  get 'about/specialists'
  get 'about/structure'
  get 'about/board'
  get 'about/partners'
  get 'about/careers'
  get 'about/reports'
  get 'about/periodics'
  get 'about/media'
  get 'about/video'
  get 'about/testimonials'

  get 'services/index'
  get 'services/show'

  get 'departments' => 'departments#index'
  get 'departments/:category' => 'departments#category', as: :department_category
  get 'departments/:category/:id' => 'departments#show', as: :department_category_department, controller: :departments
  get 'departments/:category/:id/about' => 'departments#about', as: :about_department
  get 'departments/:category/:id/patients' => 'departments#patients', as: :department_patients
  get 'departments/:category/:id/specialists' => 'departments#specialists', as: :department_specialists
  get 'departments/:category/:id/achievements' => 'departments#achievements', as: :department_achievements
  get 'departments/:category/:id/publications' => 'departments#publications', as: :department_publications
  get 'departments/:category/:id/in-the-press' => 'departments#press', as: :department_press

  get 'news' => 'news#index'
  get 'news/:id' => 'news#show', as: :news_item

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    redirect_to news_path unless @post
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/index.html.erb
<% breadcrumb :news %>

<div class="flat-title show-on-mobile">
  <h1>Новини Феофанії</h1>
</div>

<div class="article-listing">
  <% @posts.each_with_index do |post, idx| %>
      <div class="box <%= 'last' if (idx+1) % 3 == 0 %>">
        <article>
          <div class="pic">
            <% link_to news_item_path(post), title: post.title do %>
                <%= image_tag post.try(:thumbnail) || post.image, alt: post.title %>
            <% end %>
          </div>
          <div class="detail">
            <h3><%= link_to post.title, news_item_path(post), title: post.title %></h3>
            <span class="date"><%= post.date %></span>
            <p><%= raw post.subtitle %></p>
            <p><%= link_to raw('Докладніше &rarr;'), news_item_path(post), title: post.title %></p>
          </div>
        </article>
      </div>
  <% end %>

  <%= link_to raw("Завантажити більше новин <i class='icon-arrow-bottom'></i>"), news_path, class: 'loadmore' %>
</div>

app/views/news/show.html.erb
<% breadcrumb :news_item, @post %>

<div class="single">
  <h1><%= @post.title %></h1>

  <div class="news-details">
    <strong><%= @post.updated_at.strftime('%d/%m/%Y %H:%M') %></strong>
    <span class="spacer">&nbsp;</span>
    <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
    <script type="text/javascript">stLight.options({
        publisher: "ur-84b75248-af6d-8e1e-f01d-36e45a291623",
        doNotHash: false,
        doNotCopy: false,
        hashAddressBar: false
    });</script>

    <div class="share">
      <strong>Поділитися:</strong>
      <span class="spacer">&nbsp;</span>
      <span class='st_facebook_custom'></span>
      <span class="spacer">&nbsp;</span>
      <span class='st_twitter_custom'></span>
      <span class="spacer">&nbsp;</span>
      <span class='st_googleplus_custom'></span>
    </div>
  </div>

  <div>
    <%= raw @post.content %>
  </div>
</div>